export const Dataset = [

// Mobile ===========================================================================================================
  // MOTOROLA
  {
    name: "MOTOROLA g35 5G (Midnight Black, 128 GB)",
    brand: "Motorola",
    image: "https://images-eu.ssl-images-amazon.com/images/I/61Krt4z4KmL._AC_UL210_SR210,210_.jpg",
    rating: 4.3,
    category: "Mobile",
    ratingCount: "1,12,529",
    assured: true,
    discountPercent: 20,
    originalPrice: 12499,
    sellingPrice: 9999,
    wowPrice: 8999,
    exchangeOffer: "Upto ₹8,250 Off on Exchange",
    deliveryText: "EXPRESS Delivery by today, 11 PM",
    warranty: "1 year warranty by MOTOROLA",
  },
  {
    name: "MOTOROLA Edge 40 Neo 5G (Caneel Bay, 256 GB)",
    brand: "Motorola",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzZyJfwosFn6LGjLnMsYTPUBqxKx6YAygrw&s",
    rating: 4.4,
    category: "Mobile",
    ratingCount: "89,421",
    assured: true,
    discountPercent: 23,
    originalPrice: 24999,
    sellingPrice: 18999,
    wowPrice: 17999,
    exchangeOffer: "Upto ₹10,000 Off on Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "1 year warranty by MOTOROLA",
  },

  // REDMI
  {
    name: "REDMI Note 13 5G (Ice Blue, 256 GB)",
    brand: "Redmi",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTewIt6mtFb-dEEtRxUZClMypdz7q--wNKw_Q&s",
    rating: 4.4,
    category: "Mobile",
    ratingCount: "2,45,781",
    assured: true,
    discountPercent: 18,
    originalPrice: 18999,
    sellingPrice: 15499,
    wowPrice: 14999,
    exchangeOffer: "Upto ₹10,500 Off on Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "1 year warranty by Xiaomi",
  },
  {
    name: "REDMI 13C 5G (Startrail Green, 128 GB)",
    brand: "Redmi",
    image: "https://cdn.moglix.com/p/C9GhSXxqtOyWA-xxlarge.jpg",
    rating: 4.2,
    category: "Mobile",
    ratingCount: "1,95,332",
    assured: true,
    discountPercent: 26,
    originalPrice: 13999,
    sellingPrice: 10399,
    wowPrice: 9999,
    exchangeOffer: "Upto ₹7,500 Off on Exchange",
    deliveryText: "EXPRESS Delivery",
    warranty: "1 year warranty by Xiaomi",
  },

  // SAMSUNG
  {
    name: "Samsung Galaxy M14 5G (Berry Blue, 128 GB)",
    brand: "Samsung",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHd0h1PFAb65QQoCJ7I5lAhUmuPlRV8d1gKQ&s",
    rating: 4.2,
    category: "Mobile",
    ratingCount: "3,10,221",
    assured: true,
    discountPercent: 25,
    originalPrice: 15999,
    sellingPrice: 11999,
    wowPrice: 11499,
    exchangeOffer: "Upto ₹9,000 Off on Exchange",
    deliveryText: "EXPRESS Delivery",
    warranty: "1 year warranty by Samsung",
  },
  {
    name: "Samsung Galaxy F54 5G (Stardust Silver, 256 GB)",
    brand: "Samsung",
    image: "https://umiyamobile.com/wp-content/uploads/2025/05/3-71.png",
    rating: 4.3,
    category: "Mobile",
    ratingCount: "76,542",
    assured: true,
    discountPercent: 17,
    originalPrice: 34999,
    sellingPrice: 28999,
    wowPrice: 27999,
    exchangeOffer: "Upto ₹15,000 Off on Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "1 year warranty by Samsung",
  },

  // REALME
  {
    name: "realme Narzo 60 5G (Mars Orange, 128 GB)",
    brand: "Realme",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT3dO6-ff84mZwBeKluqShvXOvjMa1LuTUBg&s",
    rating: 4.3,
    category: "Mobile",
    ratingCount: "98,432",
    assured: true,
    discountPercent: 22,
    originalPrice: 17999,
    sellingPrice: 13999,
    wowPrice: 13499,
    exchangeOffer: "Upto ₹9,500 Off on Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "1 year warranty by realme",
  },
  {
    name: "realme C55 (Rainforest Green, 128 GB)",
    brand: "Realme",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzl4RyYv0aysQcxhuXCDQdT_9fZSuu8CPO1A&s",
    rating: 4.2,
    category: "Mobile",
    ratingCount: "1,65,210",
    assured: true,
    discountPercent: 30,
    originalPrice: 15999,
    sellingPrice: 11199,
    wowPrice: 10799,
    exchangeOffer: "Upto ₹8,000 Off on Exchange",
    deliveryText: "EXPRESS Delivery",
    warranty: "1 year warranty by realme",
  },

  // ONEPLUS
  {
    name: "OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB)",
    brand: "OnePlus",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv2aWcuydpkh98V-0W0_MtGzoLlXu6bCDqDw&s",
    rating: 4.2,
    category: "Mobile",
    ratingCount: "1,20,875",
    assured: true,
    discountPercent: 19,
    originalPrice: 19999,
    sellingPrice: 15999,
    wowPrice: 15499,
    exchangeOffer: "Upto ₹13,000 Off on Exchange",
    deliveryText: "EXPRESS Delivery",
    warranty: "1 year warranty by OnePlus",
  },
  {
    name: "OnePlus Nord CE 3 5G (Aqua Surge, 256 GB)",
    brand: "OnePlus",
    image: "https://img-prd-pim.poorvika.com/cdn-cgi/image/width=500,height=500,quality=75/product/oneplus-nord-4-5g-oasis-green-256gb-8gb-ram-front-back-view.png",
    rating: 4.4,
    category: "Mobile",
    ratingCount: "92,410",
    assured: true,
    discountPercent: 21,
    originalPrice: 26999,
    sellingPrice: 21499,
    wowPrice: 20999,
    exchangeOffer: "Upto ₹14,000 Off on Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "1 year warranty by OnePlus",
  },

  // ===========================================================================================================

  // boAt
  {
    name: "boAt Rockerz 550 Wireless Headphones",
    brand: "boAt",
    category: "Electronics",
    image: "https://www.boat-lifestyle.com/cdn/shop/products/64576906-013d-4af9-828a-fc3c69482a8a.png?v=1625046144",
    rating: 4.5,
    ratingCount: "5,87,442",
    assured: true,
    discountPercent: 55,
    originalPrice: 4999,
    sellingPrice: 2299,
    wowPrice: 1999,
    exchangeOffer: "No Exchange Available",
    deliveryText: "Delivery by Tomorrow",
    warranty: "1 year warranty by boAt",
  },
  {
    name: "boAt Airdopes 141 Bluetooth TWS Earbuds",
    brand: "boAt",
    category: "Electronics",
    image: "https://www.boat-lifestyle.com/cdn/shop/files/Artboard4_0e420743-5ca4-439a-9992-42347e8452b2_1800x.png?v=1747388018",
    rating: 4.3,
    ratingCount: "6,45,210",
    assured: true,
    discountPercent: 60,
    originalPrice: 4490,
    sellingPrice: 1799,
    wowPrice: 1599,
    exchangeOffer: "No Exchange Available",
    deliveryText: "EXPRESS Delivery",
    warranty: "1 year warranty by boAt",
  },

  // Sony
  {
    name: "Sony Bravia 43 inch 4K Smart LED TV",
    brand: "Sony",
    category: "Electronics",
    image: "https://rukminim2.flixcart.com/image/480/640/krme93k0/television/v/o/k/kd-43x80j-kd-43x80j-sony-original-imag5dh7jjarhbp3.jpeg?q=90",
    rating: 4.6,
    ratingCount: "98,224",
    assured: true,
    discountPercent: 30,
    originalPrice: 59999,
    sellingPrice: 41999,
    wowPrice: 39999,
    exchangeOffer: "Upto ₹15,000 Off on Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "1 year warranty by Sony",
  },
  {
    name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    brand: "Sony",
    category: "Electronics",
    image: "https://rukminim2.flixcart.com/image/480/640/xif0q/headphone/d/5/v/-original-imahgr29e7fzcfgn.jpeg?q=90",
    rating: 4.7,
    ratingCount: "45,118",
    assured: true,
    discountPercent: 25,
    originalPrice: 34990,
    sellingPrice: 26249,
    wowPrice: 25499,
    exchangeOffer: "No Exchange Available",
    deliveryText: "Delivery by Tomorrow",
    warranty: "1 year warranty by Sony",
  },

  // Samsung
  {
    name: "Samsung 28 inch 4K UHD Monitor",
    brand: "Samsung",
    category: "Electronics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRjONIl8LLxAG_Tj35x2HuREvgaJDqtlMxtA&s",
    rating: 4.4,
    ratingCount: "62,334",
    assured: true,
    discountPercent: 35,
    originalPrice: 28999,
    sellingPrice: 18899,
    wowPrice: 17999,
    exchangeOffer: "No Exchange Available",
    deliveryText: "Delivery by Tomorrow",
    warranty: "3 years warranty by Samsung",
  },
  {
    name: "Samsung 65W USB Type-C Fast Charging Adapter",
    brand: "Samsung",
    category: "Electronics",
    image: "https://images.samsung.com/is/image/samsung/p6pim/in/ep-t6530nbngin/gallery/in-65w-power-adapter-trio-ep-t6530-ep-t6530nbngin-539529006?$684_547_PNG$",
    rating: 4.5,
    ratingCount: "1,12,543",
    assured: true,
    discountPercent: 40,
    originalPrice: 3499,
    sellingPrice: 2099,
    wowPrice: 1999,
    exchangeOffer: "No Exchange Available",
    deliveryText: "EXPRESS Delivery",
    warranty: "6 months warranty by Samsung",
  },

  // LG
  {
    name: "LG 260 L Frost Free Double Door Refrigerator",
    brand: "LG",
    category: "Electronics",
    image: "https://5.imimg.com/data5/SELLER/Default/2022/11/KC/LS/FI/125978471/lg-260-l-frost-free-double-door-top-mount-3-star-refrigerator.jpeg",
    rating: 4.4,
    ratingCount: "54,129",
    assured: true,
    discountPercent: 32,
    originalPrice: 32999,
    sellingPrice: 22499,
    wowPrice: 21499,
    exchangeOffer: "Upto ₹12,000 Off on Exchange",
    deliveryText: "Delivery in 3 Days",
    warranty: "1 year product & 10 years compressor warranty",
  },
  {
    name: "LG 7 Kg 5 Star Fully Automatic Washing Machine",
    brand: "LG",
    category: "Electronics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5g8Z5sxntJI2oX7uTmnR-LZS2tBhQWC3oIw&s",
    rating: 4.3,
    ratingCount: "48,211",
    assured: true,
    discountPercent: 28,
    originalPrice: 27999,
    sellingPrice: 20199,
    wowPrice: 19499,
    exchangeOffer: "Upto ₹10,000 Off on Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "2 years comprehensive warranty by LG",
  },

  // HP
  {
    name: "HP 15s Intel Core i5 12th Gen Laptop",
    brand: "HP",
    category: "Electronics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSE27ZNPEeRcPEBbi0dS5UWvfzt47k5k23Kyw&s",
    rating: 4.2,
    ratingCount: "72,998",
    assured: true,
    discountPercent: 20,
    originalPrice: 67999,
    sellingPrice: 54399,
    wowPrice: 52999,
    exchangeOffer: "Upto ₹20,000 Off on Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "1 year onsite warranty by HP",
  },
  {
    name: "HP X1000 Wired Optical Mouse",
    brand: "HP",
    category: "Electronics",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgwJfAb4IJ7UW24_f13hybrMrPNOUlogddhA&s",
    rating: 4.4,
    ratingCount: "3,25,114",
    assured: true,
    discountPercent: 50,
    originalPrice: 999,
    sellingPrice: 499,
    wowPrice: 449,
    exchangeOffer: "No Exchange Available",
    deliveryText: "EXPRESS Delivery",
    warranty: "1 year warranty by HP",
  },

//   ============================================================================================================

  // Wakefit
  {
    name: "Wakefit Memory Foam Queen Size Mattress",
    brand: "Wakefit",
    category: "Home",
    image: "https://ik.imagekit.io/2xkwa8s1i/img/WFXGSM/WFXGSM_LS_4.jpg?tr=w-1200",
    rating: 4.4,
    ratingCount: "1,45,221",
    assured: true,
    discountPercent: 50,
    originalPrice: 18999,
    sellingPrice: 9499,
    wowPrice: 8999,
    exchangeOffer: "No Exchange",
    deliveryText: "Free Delivery by 3 Days",
    warranty: "10 years warranty by Wakefit",
  },
  {
    name: "Wakefit Adjustable Orthopedic Pillow (Set of 2)",
    brand: "Wakefit",
    category: "Home",
    image: "https://ik.imagekit.io/2xkwa8s1i/img/npl_modified_images/Wedge_pillowNew/WWPMFADB/WWPMFADB_LS_1.jpg?tr=w-3840",
    rating: 4.3,
    ratingCount: "92,418",
    assured: true,
    discountPercent: 45,
    originalPrice: 2999,
    sellingPrice: 1649,
    wowPrice: 1499,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "1 year warranty by Wakefit",
  },

  // Godrej
  {
    name: "Godrej Interio Slimline 3 Door Steel Almirah",
    brand: "Godrej",
    category: "Home",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQB5LKj1I45dOXKQDGM-ArMjv3qIhY60Y9OTg&s",
    rating: 4.2,
    ratingCount: "34,219",
    assured: true,
    discountPercent: 28,
    originalPrice: 28999,
    sellingPrice: 20899,
    wowPrice: 19999,
    exchangeOffer: "Upto ₹5,000 Off on Exchange",
    deliveryText: "Delivery in 5 Days",
    warranty: "1 year warranty by Godrej",
  },
  {
    name: "Godrej Aer Power Pocket Bathroom Fragrance (Set of 4)",
    brand: "Godrej",
    category: "Home",
    image: "https://www.bbassets.com/media/uploads/p/l/40105938_7-godrej-aer-power-pocket-long-lasting-bathroom-fragrance-floral-delight.jpg",
    rating: 4.4,
    ratingCount: "1,18,992",
    assured: true,
    discountPercent: 35,
    originalPrice: 399,
    sellingPrice: 259,
    wowPrice: 239,
    exchangeOffer: "No Exchange",
    deliveryText: "EXPRESS Delivery",
    warranty: "No Warranty",
  },

  // Prestige
  {
    name: "Prestige Deluxe Alpha Stainless Steel Pressure Cooker (5L)",
    brand: "Prestige",
    category: "Home",
    image: "https://shop.ttkprestige.com/media/catalog/product/3/8/3820-20256-IMG1.jpg?optimize=medium&fit=bounds&height=450&width=450",
    rating: 4.5,
    ratingCount: "2,35,771",
    assured: true,
    discountPercent: 40,
    originalPrice: 3999,
    sellingPrice: 2399,
    wowPrice: 2199,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "5 years warranty by Prestige",
  },
  {
    name: "Prestige Atlas 750W Mixer Grinder (3 Jars)",
    brand: "Prestige",
    category: "Home",
    image: "https://shop.ttkprestige.com/media/catalog/product/3/3/3394-42568-IMG1.jpg?optimize=medium&fit=bounds&height=450&width=450",
    rating: 4.3,
    ratingCount: "1,52,344",
    assured: true,
    discountPercent: 38,
    originalPrice: 5699,
    sellingPrice: 3539,
    wowPrice: 3399,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "2 years warranty by Prestige",
  },

  // Urban Ladder
  {
    name: "Urban Ladder Venice 3 Seater Fabric Sofa",
    brand: "Urban Ladder",
    category: "Home",
    image: "https://images-eu.ssl-images-amazon.com/images/I/71kx56BxLfL._AC_UL495_SR435,495_.jpg",
    rating: 4.1,
    ratingCount: "18,210",
    assured: true,
    discountPercent: 25,
    originalPrice: 45999,
    sellingPrice: 34499,
    wowPrice: 32999,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 7 Days",
    warranty: "1 year warranty by Urban Ladder",
  },
  {
    name: "Urban Ladder Engineered Wood Coffee Table",
    brand: "Urban Ladder",
    category: "Home",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJjsrXT5ynqUd0x9UvakA1On1G8Dgdjp34PA&s",
    rating: 4.2,
    ratingCount: "22,841",
    assured: true,
    discountPercent: 30,
    originalPrice: 11999,
    sellingPrice: 8399,
    wowPrice: 7999,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 5 Days",
    warranty: "1 year warranty by Urban Ladder",
  },

  // Philips
  {
    name: "Philips 9W LED Smart Bulb (Pack of 2)",
    brand: "Philips",
    category: "Home",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNC7XcuuNZevLQjDWphD3iaP4ZzsJGbiz2FQ&s",
    rating: 4.4,
    ratingCount: "2,95,118",
    assured: true,
    discountPercent: 55,
    originalPrice: 1299,
    sellingPrice: 579,
    wowPrice: 549,
    exchangeOffer: "No Exchange",
    deliveryText: "EXPRESS Delivery",
    warranty: "2 years warranty by Philips",
  },
  {
    name: "Philips Steam Iron GC1905 1440-Watt",
    brand: "Philips",
    category: "Home",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzFm7ZGPit5S7sU-Gstvbujpl-dxonvgpVRw&s",
    rating: 4.3,
    ratingCount: "1,08,442",
    assured: true,
    discountPercent: 42,
    originalPrice: 2499,
    sellingPrice: 1449,
    wowPrice: 1399,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "2 years warranty by Philips",
  },

  //   ============================================================================================================


  // MEN
  {
    name: "Levi's Men Slim Fit Jeans",
    brand: "Levi's",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvgH1RHTdY-KTVzcr2uth4_CppmTxjXPMtHw&s",
    rating: 4.3,
    ratingCount: "76,981",
    assured: true,
    discountPercent: 40,
    originalPrice: 2999,
    sellingPrice: 1799,
    wowPrice: 1599,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "Roadster Men Cotton Casual Shirt",
    brand: "Roadster",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTd9ugMBOLnyc1q0b78Lz-LV6eN-zpYgk-NuA&s",
    rating: 4.2,
    ratingCount: "58,210",
    assured: true,
    discountPercent: 45,
    originalPrice: 1799,
    sellingPrice: 989,
    wowPrice: 949,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "Puma Men Regular Fit Track Pants",
    brand: "Puma",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIhMpqn0C3LHqYHWMsrF5nzx-vlpF7dbgb6Q&s",
    rating: 4.4,
    ratingCount: "41,872",
    assured: true,
    discountPercent: 35,
    originalPrice: 2499,
    sellingPrice: 1624,
    wowPrice: 1549,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "HRX Men Running Sports T-Shirt",
    brand: "HRX",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCW74OpEFNsAXaUmlVUDkR-OXvyoPkKMKEkg&s",
    rating: 4.3,
    ratingCount: "63,118",
    assured: true,
    discountPercent: 50,
    originalPrice: 1499,
    sellingPrice: 749,
    wowPrice: 699,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },

  // WOMEN
  {
    name: "Biba Women Printed Anarkali Kurta",
    brand: "Biba",
    category: "Fashion",
    image: "https://assets.myntassets.com/w_412,q_30,dpr_3,fl_progressive,f_webp/assets/images/26493726/2024/2/29/0ac9543a-1d71-4ae3-8cdf-f3732edf1ff31709199269562-Biba-Floral-Printed-Pleated-Anarkali-Kurta--Churidar-With-Du-3.jpg",
    rating: 4.4,
    ratingCount: "84,332",
    assured: true,
    discountPercent: 55,
    originalPrice: 3999,
    sellingPrice: 1799,
    wowPrice: 1699,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "ONLY Women Skinny Fit Jeans",
    brand: "ONLY",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvqZhVBMwHHf17-FUs7fgK0rS-3Ez8kbpt-w&s",
    rating: 4.3,
    ratingCount: "39,874",
    assured: true,
    discountPercent: 40,
    originalPrice: 3499,
    sellingPrice: 2099,
    wowPrice: 1999,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "H&M Women Ribbed Crop Top",
    brand: "H&M",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJ40oFndZ9qxw0scpgtVrauzBMYnxsXULUZw&s",
    rating: 4.2,
    ratingCount: "52,118",
    assured: true,
    discountPercent: 30,
    originalPrice: 1499,
    sellingPrice: 1049,
    wowPrice: 999,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "Zara Women A-Line Midi Dress",
    brand: "Zara",
    category: "Fashion",
    image: "https://static.zara.net/assets/public/794d/7071/ee6f4ddc82eb/892b3521a013/08620134330-p/08620134330-p.jpg?ts=1753885471554&w=352&f=auto",
    rating: 4.5,
    ratingCount: "27,882",
    assured: true,
    discountPercent: 35,
    originalPrice: 4999,
    sellingPrice: 3249,
    wowPrice: 3099,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "Brand Warranty",
  },

  // BOYS
  {
    name: "U.S. Polo Assn Boys Casual Polo T-Shirt",
    brand: "U.S. Polo Assn",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu5SYGEWCqeuNeHkHnRGZGKwaCcQ-P0g7_aQ&s",
    rating: 4.3,
    ratingCount: "22,109",
    assured: true,
    discountPercent: 45,
    originalPrice: 1599,
    sellingPrice: 879,
    wowPrice: 829,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "Max Boys Printed Cotton Shorts",
    brand: "Max",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXYdKSRrnCQOSTukptOJKTkG2ICfOAIUEERA&s",
    rating: 4.2,
    ratingCount: "18,445",
    assured: true,
    discountPercent: 50,
    originalPrice: 999,
    sellingPrice: 499,
    wowPrice: 469,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "Puma Boys Hooded Sweatshirt",
    brand: "Puma",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwZuSzNJWvCqAofUXZuMoYy1rIEVR-wFT-Ww&s",
    rating: 4.4,
    ratingCount: "16,882",
    assured: true,
    discountPercent: 40,
    originalPrice: 2799,
    sellingPrice: 1679,
    wowPrice: 1599,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "Allen Solly Boys Slim Fit Trousers",
    brand: "Allen Solly",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm-A_cxf6mBYOoId8sB_9g6ETxeBlb7h2POw&s",
    rating: 4.3,
    ratingCount: "14,992",
    assured: true,
    discountPercent: 35,
    originalPrice: 1999,
    sellingPrice: 1299,
    wowPrice: 1249,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },

  // GIRLS
  {
    name: "Global Desi Girls Printed Ethnic Dress",
    brand: "Global Desi",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2kV-U8qmGUWLclqQ24Xzyt5yvDd6VnoRl_Q&s",
    rating: 4.4,
    ratingCount: "19,228",
    assured: true,
    discountPercent: 50,
    originalPrice: 2499,
    sellingPrice: 1249,
    wowPrice: 1199,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "Hopscotch Girls Party Wear Frock",
    brand: "Hopscotch",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqhJZd7o-KzmsACM8oJ2qy_HxWReuLrRBabw&s",
    rating: 4.5,
    ratingCount: "24,991",
    assured: true,
    discountPercent: 45,
    originalPrice: 2999,
    sellingPrice: 1649,
    wowPrice: 1599,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "H&M Girls Cotton Leggings",
    brand: "H&M",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHWtp27pREWDwYwe9MN11mqmE0L2GguAV2OA&s",
    rating: 4.2,
    ratingCount: "21,778",
    assured: true,
    discountPercent: 35,
    originalPrice: 999,
    sellingPrice: 649,
    wowPrice: 619,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },
  {
    name: "Max Girls Graphic Sweatshirt",
    brand: "Max",
    category: "Fashion",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRbQukSFkEEFNIGGV7WwuE64S5R51f-TxZmA&s",
    rating: 4.3,
    ratingCount: "17,109",
    assured: true,
    discountPercent: 40,
    originalPrice: 1599,
    sellingPrice: 959,
    wowPrice: 919,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },

  // MEN
{
  name: "Van Heusen Men Formal Slim Fit Blazer",
  brand: "Van Heusen",
  category: "Fashion",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSpJUN6R3vZI81EU3s7fPB5oQahABMTFruVg&s",
  rating: 4.4,
  ratingCount: "12,884",
  assured: true,
  discountPercent: 35,
  originalPrice: 7999,
  sellingPrice: 5199,
  wowPrice: 4999,
  exchangeOffer: "No Exchange",
  deliveryText: "Delivery in 2 Days",
  warranty: "Brand Warranty",
},

// WOMEN
{
  name: "Libas Women Cotton Kurta Pant Set",
  brand: "Libas",
  category: "Fashion",
  image: "https://assets.myntassets.com/w_412,q_30,dpr_3,fl_progressive,f_webp/assets/images/14602274/2024/4/30/821d62bd-d097-4c3f-9278-09440fab5c8b1714451757601-Libas-Women-Blue-Ethnic-Motifs-Printed-Pure-Cotton-Kurta-wit-11.jpg",
  rating: 4.5,
  ratingCount: "56,441",
  assured: true,
  discountPercent: 50,
  originalPrice: 3599,
  sellingPrice: 1799,
  wowPrice: 1699,
  exchangeOffer: "No Exchange",
  deliveryText: "Delivery by Tomorrow",
  warranty: "Brand Warranty",
},

// BOYS
{
  name: "Pepe Jeans Boys Denim Jacket",
  brand: "Pepe Jeans",
  category: "Fashion",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf33jR7PfvlKT9_MxC85jHdjROX4e0Do6Yjg&s",
  rating: 4.3,
  ratingCount: "9,774",
  assured: true,
  discountPercent: 40,
  originalPrice: 3299,
  sellingPrice: 1979,
  wowPrice: 1899,
  exchangeOffer: "No Exchange",
  deliveryText: "Delivery in 2 Days",
  warranty: "Brand Warranty",
},

// GIRLS
{
  name: "Pantaloons Girls Winter Night Suit Set",
  brand: "Pantaloons",
  category: "Fashion",
  image: "https://rukminim2.flixcart.com/image/368/490/xif0q/night-suit/y/0/8/xxl-the001-the-orange-shopee-original-imah5y2eegbrryus.jpeg?q=90&crop=false",
  rating: 4.4,
  ratingCount: "13,662",
  assured: true,
  discountPercent: 45,
  originalPrice: 1999,
  sellingPrice: 1099,
  wowPrice: 1049,
  exchangeOffer: "No Exchange",
  deliveryText: "Delivery by Tomorrow",
  warranty: "Brand Warranty",
},

  // beauty  ============================================================================================================

  // Lakme
  {
    name: "Lakme 9 to 5 Primer + Matte Lipstick",
    brand: "Lakme",
    category: "Beauty",
    image: "Lakme 9 to 5 Primer + Matte Lipstick",
    rating: 4.5,
    ratingCount: "54,882",
    assured: true,
    discountPercent: 35,
    originalPrice: 499,
    sellingPrice: 324,
    wowPrice: 299,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "Lakme 9 to 5 CC Cream SPF 30",
    brand: "Lakme",
    category: "Beauty",
    image: "https://m.media-amazon.com/images/I/51C4xyQYkwL._AC_UF1000,1000_QL80_.jpg",
    rating: 4.4,
    ratingCount: "1,12,410",
    assured: true,
    discountPercent: 30,
    originalPrice: 399,
    sellingPrice: 279,
    wowPrice: 259,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },

  // Maybelline
  {
    name: "Maybelline New York Colossal Kajal",
    brand: "Maybelline",
    category: "Beauty",
    image: "https://www.newu.in/cdn/shop/products/6946537005757_Black_I0_1024x1024.jpg?v=1671174855",
    rating: 4.6,
    ratingCount: "2,45,998",
    assured: true,
    discountPercent: 40,
    originalPrice: 199,
    sellingPrice: 119,
    wowPrice: 109,
    exchangeOffer: "No Exchange",
    deliveryText: "EXPRESS Delivery",
    warranty: "NA",
  },
  {
    name: "Maybelline Fit Me Matte + Poreless Foundation",
    brand: "Maybelline",
    category: "Beauty",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3ski02DgBOVPZDf7R35-yx30UqHDEsYUUYg&s",
    rating: 4.5,
    ratingCount: "1,89,331",
    assured: true,
    discountPercent: 28,
    originalPrice: 549,
    sellingPrice: 395,
    wowPrice: 379,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },

  // L'Oréal
  {
    name: "L'Oréal Paris Revitalift Hyaluronic Acid Serum",
    brand: "L'Oréal",
    category: "Beauty",
    image: "https://www.newu.in/cdn/shop/products/6923700977264_1_1024x1024.jpg?v=1671099109",
    rating: 4.4,
    ratingCount: "67,882",
    assured: true,
    discountPercent: 35,
    originalPrice: 999,
    sellingPrice: 649,
    wowPrice: 619,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "L'Oréal Paris Total Repair 5 Shampoo (650 ml)",
    brand: "L'Oréal",
    category: "Beauty",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG3EM_gBD0bsuXrGcgRrYoHUqbpX3oMuf0Xw&s",
    rating: 4.3,
    ratingCount: "98,114",
    assured: true,
    discountPercent: 32,
    originalPrice: 699,
    sellingPrice: 475,
    wowPrice: 449,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },

  // Mamaearth
  {
    name: "Mamaearth Onion Hair Oil for Hair Fall Control",
    brand: "Mamaearth",
    category: "Beauty",
    image: "https://assets.myntassets.com/h_1440,q_75,w_1080/v1/assets/images/27131688/2024/12/7/f7b40a87-e5d8-4227-9c9e-0ede39c14df31733576634790-Mamaearth-3-Pcs-Onion-Hair-Oil-Shampoo--Conditioner-Combo-25-1.jpg",
    rating: 4.2,
    ratingCount: "1,34,992",
    assured: true,
    discountPercent: 45,
    originalPrice: 599,
    sellingPrice: 329,
    wowPrice: 309,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "Mamaearth Ubtan Face Wash with Turmeric & Saffron",
    brand: "Mamaearth",
    category: "Beauty",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSI30z4C6toX0JZHoOUYc3kzRF_SrePhVCUdQ&s",
    rating: 4.3,
    ratingCount: "1,09,223",
    assured: true,
    discountPercent: 40,
    originalPrice: 399,
    sellingPrice: 239,
    wowPrice: 219,
    exchangeOffer: "No Exchange",
    deliveryText: "EXPRESS Delivery",
    warranty: "NA",
  },

  // Nivea
  {
    name: "Nivea Soft Light Moisturising Cream",
    brand: "Nivea",
    category: "Beauty",
    image: "https://fetchnbuy.in/cdn/shop/files/Moisturizer-JojobaOil_grande.jpg?v=1721117727",
    rating: 4.4,
    ratingCount: "2,01,118",
    assured: true,
    discountPercent: 35,
    originalPrice: 299,
    sellingPrice: 194,
    wowPrice: 179,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "Nivea Men Fresh Active Deodorant Spray",
    brand: "Nivea",
    category: "Beauty",
    image: "https://m.media-amazon.com/images/I/613amvyExPL._AC_UF350,350_QL80_.jpg",
    rating: 4.3,
    ratingCount: "88,442",
    assured: true,
    discountPercent: 38,
    originalPrice: 285,
    sellingPrice: 179,
    wowPrice: 169,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  
  //vehicel   ============================================================================================================
  // Hero
  {
    name: "Hero Xtreme 160R Bike Helmet",
    brand: "Hero",
    category: "Vehicles",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHRj59TAa4rlaIF_jDeEn2qK51NVht-Kbl9w&s",
    rating: 4.2,
    ratingCount: "18,441",
    assured: true,
    discountPercent: 45,
    originalPrice: 2499,
    sellingPrice: 1399,
    wowPrice: 1299,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "6 months warranty",
  },
  {
    name: "Hero Waterproof Bike Body Cover",
    brand: "Hero",
    category: "Vehicles",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRg75bRObPOZR7ZnYnhs4_GPH_tv9H3QUFGwQ&s",
    rating: 4.1,
    ratingCount: "25,118",
    assured: true,
    discountPercent: 40,
    originalPrice: 1999,
    sellingPrice: 1199,
    wowPrice: 1099,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "6 months warranty",
  },

  // Bosch
  {
    name: "Bosch Aerotwin Car Wiper Blade Set",
    brand: "Bosch",
    category: "Vehicles",
    image: "https://www.partsbigboss.in/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/i/m/wiper_blade_13_aerotwin_set_of_2_bosch_.jpg",
    rating: 4.4,
    ratingCount: "42,994",
    assured: true,
    discountPercent: 35,
    originalPrice: 2999,
    sellingPrice: 1949,
    wowPrice: 1849,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "1 year warranty by Bosch",
  },
  {
    name: "Bosch C70B Car Battery Charger",
    brand: "Bosch",
    category: "Vehicles",
    image: "https://m.media-amazon.com/images/I/61YR76vHQOL._AC_UF1000,1000_QL80_.jpg",
    rating: 4.3,
    ratingCount: "11,772",
    assured: true,
    discountPercent: 30,
    originalPrice: 6999,
    sellingPrice: 4899,
    wowPrice: 4699,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 3 Days",
    warranty: "1 year warranty by Bosch",
  },

  // Michelin
  {
    name: "Michelin High Performance Tubeless Car Tyre",
    brand: "Michelin",
    category: "Vehicles",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV3ExiDY17mGNfAuqgGiVLloTJSj3FWa27tA&s",
    rating: 4.5,
    ratingCount: "9,441",
    assured: true,
    discountPercent: 25,
    originalPrice: 8999,
    sellingPrice: 6749,
    wowPrice: 6499,
    exchangeOffer: "Upto ₹1,500 Off on Exchange",
    deliveryText: "Delivery in 4 Days",
    warranty: "5 years manufacturer warranty",
  },
  {
    name: "Michelin Digital Tyre Pressure Gauge",
    brand: "Michelin",
    category: "Vehicles",
    image: "https://cdn.media.halfords.com/i/washford/847308/Michelin-Programmable-Digital-Tyre-Pressure-Gauge?$sfcc_tile_featured$&w=884",
    rating: 4.3,
    ratingCount: "21,998",
    assured: true,
    discountPercent: 38,
    originalPrice: 2499,
    sellingPrice: 1549,
    wowPrice: 1449,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "1 year warranty by Michelin",
  },

  // Apollo
  {
    name: "Apollo Actigrip Bike Tyre",
    brand: "Apollo",
    category: "Vehicles",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDaBpqBKuu0bvtRNIPndMrGUBq78ktFg7o9w&s",
    rating: 4.2,
    ratingCount: "13,884",
    assured: true,
    discountPercent: 30,
    originalPrice: 2799,
    sellingPrice: 1959,
    wowPrice: 1849,
    exchangeOffer: "Upto ₹1,000 Off on Exchange",
    deliveryText: "Delivery in 3 Days",
    warranty: "3 years manufacturer warranty",
  },
  {
    name: "Apollo Tyres Portable Air Inflator",
    brand: "Apollo",
    category: "Vehicles",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgVKS-eUXMaaBFzmwubBYTiJdnWAPrgJz0UQ&s",
    rating: 4.4,
    ratingCount: "19,228",
    assured: true,
    discountPercent: 35,
    originalPrice: 3999,
    sellingPrice: 2599,
    wowPrice: 2499,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "1 year warranty by Apollo",
  },

  // Autofy
  {
    name: "Autofy Bike Mobile Holder with USB Charger",
    brand: "Autofy",
    category: "Vehicles",
    image: "https://m.media-amazon.com/images/I/71KaJPrl6hL._AC_UF1000,1000_QL80_.jpg",
    rating: 4.3,
    ratingCount: "58,119",
    assured: true,
    discountPercent: 50,
    originalPrice: 1999,
    sellingPrice: 999,
    wowPrice: 949,
    exchangeOffer: "No Exchange",
    deliveryText: "EXPRESS Delivery",
    warranty: "6 months warranty",
  },
  {
    name: "Autofy Car Dashboard Camera Full HD",
    brand: "Autofy",
    category: "Vehicles",
    image: "https://www.jiomart.com/images/product/original/rv6jdhyxgt/ausha-full-hd-dashboard-dash-cam-for-car-with-loop-recording-g-sensor-motion-detection-night-vision-car-dvr-product-images-orv6jdhyxgt-p597941938-0-202404181332.jpg?im=Resize=(420,420)",
    rating: 4.2,
    ratingCount: "14,554",
    assured: true,
    discountPercent: 40,
    originalPrice: 5999,
    sellingPrice: 3599,
    wowPrice: 3399,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "1 year warranty",
  },

  
  // sports  ============================================================================================================

  // SG
  {
    name: "SG Cricket Bat Kashmir Willow",
    brand: "SG",
    category: "Sports",
    image: "https://shop.teamsg.in/cdn/shop/files/Unnamed_design_6_b5eb4e3b-219e-49cf-b2cf-b8cf54bc6c3f.png?v=1751111960&width=1946",
    rating: 4.4,
    ratingCount: "21,342",
    assured: true,
    discountPercent: 30,
    originalPrice: 3499,
    sellingPrice: 2449,
    wowPrice: 2299,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 3 Days",
    warranty: "Manufacturer Warranty",
  },
  {
    name: "SG Test Cricket Leather Ball (Pack of 2)",
    brand: "SG",
    category: "Sports",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7UbUX5Tt7M9txfLM5yZMpgW0dkV2NKvUeOw&s",
    rating: 4.3,
    ratingCount: "18,214",
    assured: true,
    discountPercent: 35,
    originalPrice: 1599,
    sellingPrice: 1039,
    wowPrice: 999,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Manufacturer Warranty",
  },

  // Nivia
  {
    name: "Nivia Storm Football Size 5",
    brand: "Nivia",
    category: "Sports",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr8lmzqOS7G1f2JDDCxURfgd_Lm9v-cdkQDg&s",
    rating: 4.2,
    ratingCount: "32,118",
    assured: true,
    discountPercent: 40,
    originalPrice: 1299,
    sellingPrice: 779,
    wowPrice: 749,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Manufacturer Warranty",
  },
  {
    name: "Nivia Carbonite Badminton Racket",
    brand: "Nivia",
    category: "Sports",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvMmMVaVlOEmmyZdlZsrwxGjLGayKB8FCrHQ&s",
    rating: 4.3,
    ratingCount: "24,665",
    assured: true,
    discountPercent: 38,
    originalPrice: 2199,
    sellingPrice: 1369,
    wowPrice: 1299,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "Manufacturer Warranty",
  },

  // Adidas
  {
    name: "Adidas Men Running Sports Shoes",
    brand: "Adidas",
    category: "Sports",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5yfiXVG0ipkWlGYmYeCp-Emoxtl-vAvWPAQ&s",
    rating: 4.5,
    ratingCount: "45,772",
    assured: true,
    discountPercent: 35,
    originalPrice: 6999,
    sellingPrice: 4549,
    wowPrice: 4399,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 3 Days",
    warranty: "Brand Warranty",
  },
  {
    name: "Adidas Training Gym Gloves",
    brand: "Adidas",
    category: "Sports",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8uvf-3b3i-34DXxOrC2-IyUJOMv2gWYRJLw&s",
    rating: 4.4,
    ratingCount: "19,118",
    assured: true,
    discountPercent: 30,
    originalPrice: 1999,
    sellingPrice: 1399,
    wowPrice: 1349,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Brand Warranty",
  },

  // Cosco
  {
    name: "Cosco Premium Volleyball",
    brand: "Cosco",
    category: "Sports",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUwlwctf2zVXN4D_j5YnQMmFWqeBdS1yfynw&s",
    rating: 4.3,
    ratingCount: "15,442",
    assured: true,
    discountPercent: 28,
    originalPrice: 1499,
    sellingPrice: 1079,
    wowPrice: 999,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "Manufacturer Warranty",
  },
  {
    name: "Cosco Adjustable Skipping Rope",
    brand: "Cosco",
    category: "Sports",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2ZzwnEkwVAw5Sxo1O4A0eHBKILZGYS2QXQA&s",
    rating: 4.4,
    ratingCount: "88,214",
    assured: true,
    discountPercent: 45,
    originalPrice: 499,
    sellingPrice: 274,
    wowPrice: 249,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Manufacturer Warranty",
  },

  // Decathlon
  {
    name: "Decathlon Domyos Yoga Mat 8mm",
    brand: "Decathlon",
    category: "Sports",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCPFp780SNUX6az6_kNhimunmDP-FxWQ3okQ&s",
    rating: 4.5,
    ratingCount: "1,02,994",
    assured: true,
    discountPercent: 40,
    originalPrice: 1999,
    sellingPrice: 1199,
    wowPrice: 1099,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "Manufacturer Warranty",
  },
  {
    name: "Decathlon Rockrider Cycling Helmet",
    brand: "Decathlon",
    category: "Sports",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsn80ycywswfpN6LG70NOSumcI4CV9X9LkMw&s",
    rating: 4.4,
    ratingCount: "27,118",
    assured: true,
    discountPercent: 35,
    originalPrice: 2999,
    sellingPrice: 1949,
    wowPrice: 1849,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "Manufacturer Warranty",
  },


  // books   ============================================================================================================

  {
    name: "Atomic Habits by James Clear",
    brand: "James Clear",
    category: "Books",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlh7JAq4-g8M7cpagZCAyJyCmxA-8X8XqmKQ&s",
    rating: 4.7,
    ratingCount: "4,25,881",
    assured: true,
    discountPercent: 40,
    originalPrice: 599,
    sellingPrice: 359,
    wowPrice: 329,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "The Psychology of Money by Morgan Housel",
    brand: "Morgan Housel",
    category: "Books",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGBc703q0sYNdxUXgZxzgiN-I0pW_pPD7j0Q&s",
    rating: 4.6,
    ratingCount: "3,11,442",
    assured: true,
    discountPercent: 35,
    originalPrice: 499,
    sellingPrice: 324,
    wowPrice: 299,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "Rich Dad Poor Dad by Robert Kiyosaki",
    brand: "Robert Kiyosaki",
    category: "Books",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXQU7IvvJEuYGyRkZKxd--__xDnUmibOOH5A&s",
    rating: 4.6,
    ratingCount: "5,12,118",
    assured: true,
    discountPercent: 45,
    originalPrice: 699,
    sellingPrice: 384,
    wowPrice: 359,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "Ikigai by Hector Garcia & Francesc Miralles",
    brand: "Hector Garcia",
    category: "Books",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjaid2IRXRvR5L42msCI6Ddzt68nABHoKB-g&s",
    rating: 4.5,
    ratingCount: "2,95,771",
    assured: true,
    discountPercent: 38,
    originalPrice: 499,
    sellingPrice: 309,
    wowPrice: 289,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "Think Like a Monk by Jay Shetty",
    brand: "Jay Shetty",
    category: "Books",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Iju9NczA06g6PP6o9DKjcIZMPpK1EeH5TQ&s",
    rating: 4.4,
    ratingCount: "1,88,442",
    assured: true,
    discountPercent: 30,
    originalPrice: 499,
    sellingPrice: 349,
    wowPrice: 329,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "The Alchemist by Paulo Coelho",
    brand: "Paulo Coelho",
    category: "Books",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz_LjCHPGl5Xm2tO2TiNf01LRqbvUBRT_5gQ&s",
    rating: 4.6,
    ratingCount: "6,45,331",
    assured: true,
    discountPercent: 42,
    originalPrice: 399,
    sellingPrice: 229,
    wowPrice: 219,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "Harry Potter and the Philosopher's Stone",
    brand: "J.K. Rowling",
    category: "Books",
    image: "https://www.crossword.in/cdn/shop/products/crosswordonline-books-default-name-harry-potter-and-the-philosopher-s-stone-j-k-rowling-40421717704921.jpg?v=1745732396",
    rating: 4.8,
    ratingCount: "7,88,991",
    assured: true,
    discountPercent: 35,
    originalPrice: 499,
    sellingPrice: 324,
    wowPrice: 299,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "The Power of Your Subconscious Mind by Joseph Murphy",
    brand: "Joseph Murphy",
    category: "Books",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyqufoRYmCymny12QSnbYlbMBiyj_3hhBT8Q&s",
    rating: 4.5,
    ratingCount: "4,01,229",
    assured: true,
    discountPercent: 50,
    originalPrice: 399,
    sellingPrice: 199,
    wowPrice: 189,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "Do Epic Shit by Ankur Warikoo",
    brand: "Ankur Warikoo",
    category: "Books",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXA-qA1Xjg5ZeKtlT9LPexzWvzgYzVgXRv7w&s",
    rating: 4.4,
    ratingCount: "1,55,884",
    assured: true,
    discountPercent: 30,
    originalPrice: 499,
    sellingPrice: 349,
    wowPrice: 329,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },
  {
    name: "NCERT Class 10 Science Textbook",
    brand: "NCERT",
    category: "Books",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH_hp2pUHgcWP10xT8kzb81gwpNhGVhyvgzQ&s",
    rating: 4.3,
    ratingCount: "92,118",
    assured: true,
    discountPercent: 20,
    originalPrice: 250,
    sellingPrice: 199,
    wowPrice: 189,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },


  // toys   ============================================================================================================

  // LEGO
  {
    name: "LEGO Classic Creative Bricks Set",
    brand: "LEGO",
    category: "Toys",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqDcAxZvcjDCZO4FARFOStx132eBg1zOfI6w&s",
    rating: 4.8,
    ratingCount: "32,781",
    assured: true,
    discountPercent: 20,
    originalPrice: 1499,
    sellingPrice: 1199,
    wowPrice: 1099,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "NA",
  },
  {
    name: "LEGO City Police Patrol Car",
    brand: "LEGO",
    category: "Toys",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkhhZyyoGvyhhWLP6SfSeKlyHzzN7GG9mLYg&s",
    rating: 4.7,
    ratingCount: "21,118",
    assured: true,
    discountPercent: 25,
    originalPrice: 1999,
    sellingPrice: 1499,
    wowPrice: 1399,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },

  // Hot Wheels
  {
    name: "Hot Wheels Track Builder Mega Pack",
    brand: "Hot Wheels",
    category: "Toys",
    image: "https://m.media-amazon.com/images/I/61vJ-M6jldL.jpg",
    rating: 4.6,
    ratingCount: "44,221",
    assured: true,
    discountPercent: 30,
    originalPrice: 2499,
    sellingPrice: 1749,
    wowPrice: 1649,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "NA",
  },
  {
    name: "Hot Wheels Monster Truck Toy Car",
    brand: "Hot Wheels",
    category: "Toys",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbD9D9b8eC9E8CC3y1KacXjOUyWwwaxlOLqw&s",
    rating: 4.5,
    ratingCount: "39,882",
    assured: true,
    discountPercent: 35,
    originalPrice: 899,
    sellingPrice: 584,
    wowPrice: 549,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },

  // Funskool
  {
    name: "Funskool Doctor Play Set",
    brand: "Funskool",
    category: "Toys",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDAzZuZHFYEcUWEIrHTe38Q3HYFhNG53fuWQ&s",
    rating: 4.4,
    ratingCount: "18,771",
    assured: true,
    discountPercent: 40,
    originalPrice: 1199,
    sellingPrice: 719,
    wowPrice: 679,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 3 Days",
    warranty: "NA",
  },
  {
    name: "Funskool Educational Building Blocks",
    brand: "Funskool",
    category: "Toys",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWkGxCKehvCXA2Z9DzRauIJAa7vMk2-jClXA&s",
    rating: 4.5,
    ratingCount: "25,441",
    assured: true,
    discountPercent: 45,
    originalPrice: 1599,
    sellingPrice: 879,
    wowPrice: 829,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },

  // Barbie
  {
    name: "Barbie Dreamtopia Princess Doll",
    brand: "Barbie",
    category: "Toys",
    image: "https://images-cdn.ubuy.co.in/67dcf022484bcf032521a866-barbie-dreamtopia-doll.jpg",
    rating: 4.7,
    ratingCount: "41,115",
    assured: true,
    discountPercent: 35,
    originalPrice: 1999,
    sellingPrice: 1299,
    wowPrice: 1249,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "NA",
  },
  {
    name: "Barbie Fashion Accessories Pack",
    brand: "Barbie",
    category: "Toys",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLnOrjyvGp6Iw05e2qgmeUlvc7Ffx1YVp6oQ&s",
    rating: 4.6,
    ratingCount: "22,884",
    assured: true,
    discountPercent: 30,
    originalPrice: 1299,
    sellingPrice: 909,
    wowPrice: 869,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery by Tomorrow",
    warranty: "NA",
  },

  // Fisher-Price
  {
    name: "Fisher-Price Laugh & Learn Smart Tablet",
    brand: "Fisher-Price",
    category: "Toys",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDj_lnPYb6uXXa7v4zmNG4WiDMAUoawgdW8Q&s",
    rating: 4.6,
    ratingCount: "53,112",
    assured: true,
    discountPercent: 28,
    originalPrice: 2499,
    sellingPrice: 1799,
    wowPrice: 1699,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 2 Days",
    warranty: "NA",
  },
  {
    name: "Fisher-Price Musical Activity Walker",
    brand: "Fisher-Price",
    category: "Toys",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSprDbemmreYexpkUJnjue1Rq1U0_WRpOrLig&s",
    rating: 4.7,
    ratingCount: "36,441",
    assured: true,
    discountPercent: 32,
    originalPrice: 3999,
    sellingPrice: 2719,
    wowPrice: 2599,
    exchangeOffer: "No Exchange",
    deliveryText: "Delivery in 3 Days",
    warranty: "NA",
  },



];
